name: terraform

on: workflow_dispatch

env:
    TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    TF_VAR_aws_access_secret_id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    run-terraform-plan:

        name: "tf-destroy"

        runs-on: ubuntu-latest

        defaults:
            run:
              working-directory: ${{ github.workspace }}/terraform/
        permissions:
            pull-requests: write
        steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1      

        - uses: actions/checkout@v4
        - uses: hashicorp/setup-terraform@v3

        - name: Terraform Destroy
          id: init
          run: terraform destroy --auto-approve